import type { Steps } from "../types";

export const steps: Steps[] = [
  {
    id: 0,
    title: "Realizar proposta",
    professorTitle: "Realizando proposta",
    description: "Preencha os dados abaixo para publicar sua proposta de TCC.",
    buttonText: "Enviar proposta",
    deliveryType: "PROPOSTA",
  },
  {
    id: 1,
    title: "Proposta em avaliação pelo Orientador",
    professorTitle: "Disponível para avaliação",
    description: "Aguarde a avaliação da sua proposta pelo Orientador.",
    buttonText: "Atualizar proposta",
    deliveryType: undefined,
  },
  {
    id: 2,
    title: "Proposta reprovada - Realizar reelaboração da proposta",
    professorTitle: "Proposta reprovada - Aguardando reelaboração de proposta",
    description: "Atualize os dados da sua proposta e envie novamente para avaliação.",
    buttonText: "Reenviar proposta",
    deliveryType: "REELABORACAO_PROPOSTA",
  },
  {
    id: 3,
    title: "Proposta aceita - Realizar entrega do TCC",
    professorTitle: "Proposta aceita - Aguardando entrega de TCC",
    description: "Preencha os dados abaixo para entregar seu TCC.",
    buttonText: "Entregar TCC",
    deliveryType: "TC",
  },
  {
    id: 4,
    title: "Admissibilidade em avaliação pelo Orientador",
    professorTitle: "TCC disponível para parecer de admissibilidade",
    description: "Aguarde a avaliação de admissibilidade do seu TCC pelo Orientador.",
    buttonText: undefined,
    deliveryType: undefined,
  },
  {
    id: 5,
    professorTitle: "Admissibilidade reprovada - Aguardando atualização do TCC",
    title: "Admissibilidade reprovada - Realizar atualização do TCC",
    description: "Atualize os dados do seu TCC e envie novamente para avaliação.",
    buttonText: "Atualizar TCC",
    deliveryType: undefined,
  },
  {
    id: 6,
    title: "TCC em avaliação",
    professorTitle: "TCC em avaliação pela banca examinadora",
    description: "Aguarde a avaliação do seu TCC pela banca examinadora.",
    buttonText: undefined,
    deliveryType: undefined,
  },
  {
    id: 7,
    title: "TCC reprovado - Realizar reelaboração do TCC",
    professorTitle: "TCC reprovado - Aguardando reelaboração do TCC",
    description: "Atualize os dados do seu TCC e envie novamente para avaliação.",
    buttonText: "Reenviar TCC",
    deliveryType: "REELABORACAO_TC",
  },
  {
    id: 8,
    title: "TCC aceito",
    professorTitle: "TCC aceito pela banca examinadora",
    description: "Parabéns! Seu TCC foi aceito pela banca examinadora.",
    buttonText: undefined,
    deliveryType: undefined,
  },
];
