import type { Steps } from "../types";

export const steps: Steps[] = [
  {
    id: 0,
    title: "Realizar proposta",
    professorTitle: "Realizando proposta",
    description: "Preencha os dados abaixo para publicar sua proposta de TCC.",
    buttonText: "Enviar proposta",
    deliveryType: "PROPOSTA",
    shouldShowEvaluationDetails: false,
    shouldShowEvaluationForm: false,
    shouldShowDeliveryForm: true,
    shouldShowChangeAdmissibility: false,
    shouldShowDonwnloadFileButton: false,
  },
  {
    id: 1,
    title: "Proposta em avaliação pelo Orientador",
    professorTitle: "Disponível para avaliação",
    description: "Aguarde a avaliação da sua proposta pelo Orientador.",
    buttonText: "Atualizar proposta",
    deliveryType: undefined,
    shouldShowEvaluationDetails: true,
    shouldShowEvaluationForm: true,
    shouldShowDeliveryForm: true,
    shouldShowChangeAdmissibility: false,
    shouldShowDonwnloadFileButton: true,
  },
  {
    id: 2,
    title: "Proposta reprovada - Realizar reelaboração da proposta",
    professorTitle: "Proposta reprovada - Aguardando reelaboração de proposta",
    description:
      "Atualize os dados da sua proposta e envie novamente para avaliação.",
    buttonText: "Reenviar proposta",
    deliveryType: "REELABORACAO_PROPOSTA",
    shouldShowEvaluationDetails: true,
    shouldShowEvaluationForm: false,
    shouldShowDeliveryForm: true,
    shouldShowChangeAdmissibility: false,
    shouldShowDonwnloadFileButton: true,
  },
  {
    id: 3,
    title:
      "Admissibilidade em avaliação pelo Orientador ou número mínimo de reuniões não atingido",
    professorTitle:
      "TCC disponível para parecer de admissibilidade ou número mínimo de reuniões não atingido",
    description:
      "Aguarde a avaliação de admissibilidade do seu TCC pelo Orientador e o mínimo de 6 reuniões de orientação realizada.",
    buttonText: undefined,
    deliveryType: undefined,
    shouldShowEvaluationDetails: true,
    shouldShowDeliveryForm: false,
    shouldShowEvaluationForm: false,
    shouldShowChangeAdmissibility: true,
  },
  {
    id: 4,
    title: "Paracer de Admissibilidade realizado - Realize a entrega do TCC",
    professorTitle:
      "Parecer de Admissibilidade realizado - Aguardando entrega de TCC",
    description: "Preencha os dados abaixo para entregar seu TCC.",
    buttonText: "Entregar TCC",
    deliveryType: "TC",
    shouldShowEvaluationDetails: false,
    shouldShowDeliveryForm: true,
    shouldShowEvaluationForm: false,
    shouldShowChangeAdmissibility: true,
    shouldShowDonwnloadFileButton: false,
  },
  {
    id: 5,
    title: "TCC em avaliação",
    professorTitle: "TCC em avaliação pela banca examinadora",
    description: "Aguarde a avaliação do seu TCC pela banca examinadora.",
    buttonText: undefined,
    deliveryType: undefined,
    shouldShowEvaluationDetails: true,
    shouldShowDeliveryForm: true,
    shouldShowEvaluationForm: true,
    shouldShowChangeAdmissibility: true,
    shouldShowDonwnloadFileButton: true,
  },
  {
    id: 6,
    title: "TCC reprovado - Realizar reelaboração do TCC",
    professorTitle: "TCC reprovado - Aguardando reelaboração do TCC",
    description:
      "Atualize os dados do seu TCC e envie novamente para avaliação.",
    buttonText: "Reenviar TCC",
    deliveryType: "REELABORACAO_TC",
    shouldShowEvaluationDetails: true,
    shouldShowDeliveryForm: true,
    shouldShowEvaluationForm: false,
    shouldShowChangeAdmissibility: true,
    shouldShowDonwnloadFileButton: true,
  },
  {
    id: 7,
    title: "TCC aceito",
    professorTitle: "TCC aceito pela banca examinadora",
    description: "Parabéns! Seu TCC foi aceito pela banca examinadora.",
    buttonText: undefined,
    deliveryType: undefined,
    shouldShowEvaluationDetails: true,
    shouldShowDeliveryForm: true,
    shouldShowEvaluationForm: false,
    shouldShowChangeAdmissibility: true,
    shouldShowDonwnloadFileButton: false,
  },
];
