export const AppQueryKeys = {
  PERSONAL_INFO: 'personal-info',
  USERS: 'users',
  ONE_USER: 'one-user',
  TCCS: 'tccs',
  TCC_RELATIONSHIP: 'tccRelationship',
  DELIVERIES: 'deliveries',
  EVALUATION: 'evaluation',
  MEETINGS: 'meetings',
  NOTIFICATIONS: 'notifications',
  MEETINGS_DETAILS: 'meeting-details',
  LIMITED_NOTIFICATIONS: 'limited-notifications',
  LIMITED_MEETINGS: 'limited-meetings',
} as const;

export const AppMutationKeys = {
  LOGIN: 'login',
  REGISTER: 'register',
  UPDATE_PROFILE: 'update-profile',
  DELETE_USER: 'delete-user',
  DELETE_TCC: 'delete-tcc',
  UPDATE_CREATE_TCC: 'update-create-tcc',
  CREATE_DELIVERY: 'create-delivery',
  UPDATE_DELIVERY: 'update-delivery',
  DOWNLOAD_FILE: 'download-file',
  CREATE_EVALUATION: 'create-evaluation',
  UPDATE_EVALUATION: 'update-evaluation',
  CREATE_MEETING: 'create-meeting',
  CHANGE_ADMISSIBILITY: 'change-admissibility',
  CANCEL_MEETING: 'cancel-meeting',
  UPLOAD_DOCUMENT: 'upload-document',
  MARK_AS_READ: 'mark-as-read',
  DELETE_NOTIFICATION: 'delete-notification',
  MARK_ALL_AS_READ: 'mark-all-as-read',
} as const;